apiVersion: apps/v1
kind: Deployment
metadata:
  name: aff-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aff-app-mongo
  template:
    metadata:
      labels:
        app: aff-app-mongo
    spec:
      containers:
      - name: nodejs-app
        image: dimple200103/aff-nodejs:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/AFF-Docker"
        - name: PORT
          value: "3015"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "AFF-Docker"