apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer # Use ClusterIP or NodePort based on your requirements
  ports:
    - port: 3015
      targetPort: 3015
  selector:
    app: aaff-app-mongo